### ISSUE TITLE
Use native package managers

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#106]
_Originally posted by @2bndy5 in this thread https://github.com/cpp-linter/clang-tools-pip/issues/32_

Found out that we could use chocolatey to install LLVM binaries on Windows runners https://community.chocolatey.org/packages/llvm#versionhistory
The pkg manager chocolatey is already installed on the Windows runners.

Not sure about the future of this pkg since we could use
- `choco` for Windows,
- `apt` for Linux,
- and what could be used for Mac? Maybe `homebrew`? I don't give Apple any of my money, so I have no way to test `homebrew` locally.

All of these pkg managers could be used directly in the composite action's steps.
```yml
steps:
   - name: Install Binaries (Linux)
     if: runner.os == 'Linux'
     run: sudo apt-get install clang-tidy-${{ inputs.version }} clang-format-${{ inputs.version }}
   - name: Install Binaries (Windows)
     if: runner.os == 'Windows'
     # this may require the full version tag (`12.0.0` instead of `12`)
     run: choco install llvm --version ${{ inputs.version }} -y
   - name: Install Binaries (macOS)
     if: runner.os == 'macOS'
     # TBD
     run: homebrew install ???
```
