### ISSUE TITLE
Why all checks have passed?

### ISSUE THREAD

**Issue by pypygeek** [cpp-linter/cpp-linter-action#117]
hello,

Why all checks have passed?

I want to raise an error if the ansi rule is not met.

```yml
name: C Code Convention CI

on: [push]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          extensions: c,C,h,H
          extra-args: -Wall -Wextra -ansi -c

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
```

![image](https://user-images.githubusercontent.com/19469996/198834118-d00a3f5c-592f-45c5-90b7-17bd4c01df1a.png)
[Create a.c](https://github.com/pypygeek/action_test/pull/1/files)
