### ISSUE TITLE
Improve paths handling

### ISSUE THREAD

**Issue by ivancho-ifa** [cpp-linter/cpp-linter-action#155]
First of all, great Action!

I noticed that when setting an absolute path to the compilation database I receive wrong paths.
```yml
    - name: Run clang-tidy and clang-format 
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          style: file
          database: ${{github.workspace}}/out/build/${{matrix.arch}}-${{env.BUILD_TYPE}}
          thread-comments: true
          step-summary: true
```
Produces `"D:\a\figures-counter\figures-counter\afigures-counterfigures-counter\out\build\x64-debug"` instead of the correct path `"D:\a\figures-counter\figures-counter\out\build\x64-debug"`

The workaround is to omit the prefix and use relative path 
```yml
database: out/build/${{matrix.arch}}-${{env.BUILD_TYPE}}
```
