### ISSUE TITLE
How to make cpp-linter-action work with Conan?

### ISSUE THREAD

**Issue by skhaz** [cpp-linter/cpp-linter-action#167]
I have been using Conan 2 successfully on Windows, Linux (Ubuntu), and macOS (x86_64 & arm64); however, when attempting to use it with `cpp-linter-action`, it seems that the linter cannot find the headers and libraries installed by Conan, as can be seen below.

My question is: How can I make the `cpp-linter-action` recognize the inclusion paths? Is there a way to specify "This is a project that uses CMake, use the CMake directives"?

Error:

```shell
 /home/runner/work/carimbo/carimbo/src/common.hpp:12:10: error: 'SDL2/SDL.h' file not found [clang-diagnostic-error]
  #include <SDL2/SDL.h>
           ^
```

Logs: https://github.com/carimbolabs/carimbo/actions/runs/6904880635/job/18786474539

Workflow:

```yaml
name: Lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan2/p
            ~\.conan/p
          key: ${{ runner.os }}

      - name: Prepare Build Directory
        run: mkdir build

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Conan
        run: pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Install Ubuntu Dependencies
        run: sudo apt-get install -y libegl-dev libegl1-mesa-dev libva-dev libvdpau-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-util-dev

      - name: Install Dependencies
        run: conan install ..  --output-folder=. --build="*" --settings compiler.cppstd=17 --settings build_type=Release
        working-directory: build

      - name: Lint
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file

      - name: Fail Fast
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
```

**Comment by 2bndy5** [comment]
You need to have CMake generate a compilation database. This database is basically a list of compiler commands for each file that clang-tidy can use to find third party libraries.

Add the line to your root CMakeLists.text:
```
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
```

**Comment by skhaz** [comment]
I already have this flag

https://github.com/carimbolabs/carimbo/blob/77c55561bb32d1b9d5c2d0fd6d165ac7f7865ec3/CMakeLists.txt#L17

**Comment by 2bndy5** [comment]
Please reread the later half of my last comment. I accidentally posted before I was done typing.

**Comment by 2bndy5** [comment]
BTW, its also pretty important to specify what version of clang you are using. There are some significant differences between major versions of clang-format/tidy.

**Comment by skhaz** [comment]
@2bndy5, thank you for the assistance; I discovered an issue with the output—it was set to `--output-folder=.` and not `--output-folder=build`.

Changing it resolved the problem.

Below is the complete workflow for anyone wishing to use this excellent linter with Conan.

```
name: Lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan2/p
          key: ${{ runner.os }}-${{ hashFiles('**/conanfile.txt') }}

      - name: Prepare Build Directory
        run: mkdir build

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Conan
        run: pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Install Ubuntu Dependencies
        run: sudo apt-get install -y libegl-dev libegl1-mesa-dev libva-dev libvdpau-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-util-dev

      - name: Install Dependencies
        run: conan install ..  --output-folder=build --build=missing --settings compiler.cppstd=17 --settings build_type=Release
        working-directory: build

      - name: Lint
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          ignore: build
          database: build
          extra-args: -std=c++17 -Wall
```
