### ISSUE TITLE
Complaints regarding code formatting but no diff suggested

### ISSUE THREAD

**Issue by Alexolut** [cpp-linter/cpp-linter-action#250]
I have code like this, formatted locally with clang-format. I use function-try-block here:
```
void TestFunc(const std::string& data) try {
    do_something();
    do_something_more();
} catch (const std::exception& ex) {
    log_error(ex);
}
```

cpp-linter has complaints on this code, pointing to the line with `catch` (99):
``` 
Notice: File filename.cpp does not conform to Custom style guidelines. (lines 99)
```

At the same time I don't see any diff suggestions in PR despite I have `format-review: true` and if I intentionally add wrongly-formatted changes on other lines - I will see only diff for those lines (but line with `catch` still won't be in diff for some reason).

Full list of options that I use:
```
        uses: cpp-linter/cpp-linter-action@v2.12.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: '-*'
          version: '18'
          step-summary: true
          lines-changed-only: true
          format-review: true
          passive-reviews: true
          thread-comments: update
```

Looks like everything is OK with formatting, but cpp-linter mark that code as not-formatted.

**Comment by 2bndy5** [comment]
What does the review summary comment say? The `format-review` feature should attach a full diff of desired changes in the review's summary comment. It would be collapsed under the text "Click here for the full clang-format patch". For example: https://cpp-linter.github.io/cpp-linter-action/images/format-review.png

I have to ask, what triggers are used by your CI workflow? I think I asked you this before but got no answer. For example the triggers are under the yaml field `on`: 
```yaml
on:
  pull_request:
    branches: [main, master, develop]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake']
  push:
    branches: [main, master, develop]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake']
```
