### ISSUE TITLE
remove added LLVM apt PPA

### ISSUE THREAD

**Issue by 2bndy5** [cpp-linter/cpp-linter-action#265]
### Is your idea related to an existing feature?

version

### Describe the behavior you would like

I noticed that the LLVM install script (for Debian Linux OS) cannot be used more than once in a single workflow run.  This means users will have an error if
```yaml
runs-on: ubuntu-latest
steps:
  - uses: cpp-linter/cpp-linter-action@v2
    with:
      version: 16
  # re-run action in same workflow with different clang version
  - uses: cpp-linter/cpp-linter-action@v2
    with:
      # ERROR: the LLVM PPA repo is already set to use v16 from previous step
      version: 19
```

The error would look something like:
> E: The repository 'http://apt.llvm.org/jammy llvm-toolchain-jammy-16 Release' does not have a Release file.

I solved this problem by removing the LLVM PPA repo after we install clang-tidy and clang-format from it:
```sh
sudo rm /etc/apt/sources.list.d/*llvm*.list || true
```

### Describe alternatives you have considered

I did consider adding the LLVM apt PPA repo manually. However, the install script takes care of a lot of other cross-distribution problems, namely determining which derivative/flavor of Debian is used. Using the install script still relieves some tech debt as it is well maintained by the LLVM project.

### Additional context

The updated source of the LLVM install script can be examined from https://apt.llvm.org/llvm.sh.

The scenario in which cpp-linter-action might be used more than once in a single workflow depends on the project being analyzed. As an example, a user might want to examine different sources using different compilation databases. Ultimately, the cpp-linter python package is not well suited for multiple uses in a single CI event, but that is an issue (or multitude of issues) for another time.
