### ISSUE TITLE
Fails to parse diff when a file has many (or no) changes

### ISSUE THREAD

**Issue by rturrado** [cpp-linter/cpp-linter-action#274]
### What events trigger your workflow?

```yml
on:
  push:
    branches:
      - develop
      - master
  pull_request:
```

### What OS does your workflow use?

```yml
runs-on: ubuntu-latest
```

### How is cpp-linter-action configured?

```yml
jobs:
  cpp-linters:
    name: "C++ linters"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run C++ linters
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extensions: 'cpp,hpp'
          format-review: 'true'
          style: 'file'  # use .clang-format config file
          tidy-checks: '-*'  # disable clang-tidy checks
          version: 18
      - name: Fail fast
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: |
          echo "::notice::Try executing 'python3 ./scripts/run_cpp_linters.py .' to fix linter issues."
          exit 1

I initially had also the option `files-changed-only: 'false'`. I took it out but the error remains.
```

### What was the unexpected behavior?

I'm getting this error from GitHub Actions:

```
ERROR:CPP Linter:response returned 406 from GET https://api.github.com/repos/QuTech-Delft/libqasm/pulls/263 with message: {"message":"Sorry, the diff exceeded the maximum number of files (300). Consider using 'List pull requests files' API or locally cloning the repository instead.","errors":
```

You can see the full log here: https://github.com/QuTech-Delft/libqasm/actions/runs/11381786455/job/31663943797

I'm updating a `master` branch from a `develop` branch, and the PR includes over 500 files. But I don't see how that can affect the C++ linters.

**Comment by rturrado** [comment]
A possible solution from people experiencing the same issue: https://github.com/reviewdog/reviewdog/issues/1696#issuecomment-2134523011

**Comment by 2bndy5** [comment]
According to the logs, the real problem is that a file in the list of changed files did not include the patch info. Let's walk through the logs.

> ERROR:CPP Linter:response returned 406 from GET https://api.github.com/repos/QuTech-Delft/libqasm/pulls/263 with message: {"message":"Sorry, the diff exceeded the maximum number of files (300). Consider using 'List pull requests files' API or locally cloning the repository instead.","errors":[{"resource":"PullRequest","field":"diff","code":"too_large"}],"documentation_url":"https://docs.github.com/rest/pulls/pulls#list-pull-requests-files","status":"406"}
  INFO:CPP Linter:Could not get raw diff of the pull_request event. Perhaps there are too many changes?

This means the at you hit the problem reported in #249.  The solution to that was to fall back to using GitHub's REST API in which each file's did was parsed individually. 

> ERROR:CPP Linter:Using pure python to parse diff because pygit2 failed!
  WARNING:CPP Linter:pygit2.Diff.parse_diff() threw invalid patch instruction at line ...

These repeated errors warnings just mean that libgit2 python binding failed to parse the files' individual diff (which we have to assemble on the fly with limited information about each file's patch). This uses brute force regex patterns instead of libgit2's diff parsing algorithm. But then we find a file that doesn't include any patch information: 

```python
Traceback (most recent call last):
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/bin/cpp-linter", line 8, in <module>
      sys.exit(main())
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/__init__.py", line 46, in main
      files = rest_api_client.get_list_of_changed_files(
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/github_api.py", line 108, in get_list_of_changed_files
      return self._get_changed_files_paginated(
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/github_api.py", line 144, in _get_changed_files_paginated
      assert "patch" in file
  AssertionError
```

This is one of the reasons we originally switched to getting the raw diff of the event instead of parsing each changed file's patch. It means that GitHub refused to give us the patch for a file with too many changes.

## Workaround
If you expect all your PRs to have a large diff, then you should disable any features that rely on having diff information.
```yml
- uses: cpp-linter/cpp-linter-action@v2
  id: linter
  with:
    lines-changed-only: false
    files-changed-only: false
    format-review: false
    tidy-review: false
```

## possible solution on our end

I guess we could silently fail when a file's diff is unknown, but that will cause further unexpected behavior (like unreported syntax/format errors in files with too many changes). If GitHub won't give us the information we need, then we can't be expected to operate correctly. I have to investigate more...

I think it would simply be better to improve the error message output. We should point to the file that didn't include the patch in the REST API's response.
