### ISSUE TITLE
Allow colored logging output via CPP_LINTER_COLOR env var

### ISSUE THREAD

**Issue by 2bndy5** [cpp-linter/cpp-linter-action#275]
### Is your idea related to an existing feature?

verbosity

### Describe the behavior you would like

The logs can be rather monotonous when looking for errors.

The cpp-linter python package already has support for using the [`rich` package][rich] to add color and style to log outputs. This action only needs to ensure [`rich`][rich] is installed if users want colored (and stylized) output in the CI logs.

[rich]: https://pypi.org/project/rich/

### Proposal
```yml
- uses: cpp-linter/cpp-linter-action@v2
  env:
    # enabled colored output in logs (uses `rich` package)
    CPP_LINTER_COLOR: true
```

Acceptable values that mean "color enabled" include `true`, `on`, and `1`. By default, color output should be disabled because the ASCII color codes are included in the raw logs that can be downloaded to a text file.

### Additional context

The cpp-linter-rs project already includes support for this env variable (see cpp-linter/cpp-linter-rs#52), and it does not require additional dependencies installed. Migrating this new feature to use the rust project should be seamless.
