### ISSUE TITLE
v3 action check fails

### ISSUE THREAD

**Issue by mexikoedi** [cpp-linter/cpp-linter-action#284]
### What events trigger your workflow?

```yml
on: push
```

### What OS does your workflow use?

```yml
runs-on: ubuntu-latest
```

### How is cpp-linter-action configured?

```yml
- uses: actions/checkout@v4.2.2
- uses: cpp-linter/cpp-linter-action@v3
  id: linter
  env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
       style: file
```

### What was the unexpected behavior?

 I am using this action in a repository and cpp-linter-action@v2 was updated to cpp-linter-action@v3 by dependabot and now the check fails. I didn't change anything else and the error which appears doesn't help either.
 I get the following error: `error: a value is required for '--database <database>' but none was supplied`.
 Which happens after `Run source "$GITHUB_ACTION_PATH/venv/bin/activate`.
 Do I need to configure something or how can I fix this issue? 
 I couldn't find any information for v3 or this error.
