### ISSUE TITLE
Lines-changed-only seems not to work for clang-tidy

### ISSUE THREAD

**Issue by regit** [cpp-linter/cpp-linter-action#297]
### What events trigger your workflow?

```yml
on:
  pull_request:
    branches: [master]
    paths: ['**.c', '**.h', '**.am']
  push:
    paths: ['**.c', '**.h', '**.am']
```

### What OS does your workflow use?

```yml
runs-on: ubuntu-latest
container: ubuntu:22.04
```

### How is cpp-linter-action configured?

```yml
- uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: '' # Empty for no format check
          tidy-checks: '' # Use .clang-tidy config file. 
          version: ${{ env.LLVM_VERSION }}
          # only 'update' a single comment in a pull request's thread. 
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          lines-changed-only: true
          tidy-review: true
          passive-reviews: true
```

### What was the unexpected behavior?

I'm testing the action and it seems to detect correctly the line changed in the file I did update to trigger some error.

The job is running the command:
```
/usr/bin/clang-tidy-14 --line-filter=[{"name": "src/source-af-packet.c", "lines": [[1, 2], [932, 935], [940, 943]]}] --extra-arg= --fix-errors src/source-af-packet.c
```
which returns no warning despite the introduction of invalid code in these places.

When I run a derivated same command on my system:
```
clang-tidy --line-filter='[{"name": "src/source-af-packet.c", "lines": [[1, 2], [932, 935], [940, 943]]}]' --extra-arg= src/source-af-packet.c
```
I got no error too but if I do
```
clang-tidy --line-filter='[{"name": "source-af-packet.c", "lines": [[1, 2], [932, 935], [940, 943]]}]' --extra-arg= src/source-af-packet.c
```
then I got the correct behavior.

Is there an option to skip the source directory in the action ?

Failing job url: https://github.com/regit/suricata/actions/runs/14709331910/job/41277429460

**Comment by 2bndy5** [comment]
> [!tip]
> 1. clang-tidy always works better when you give it a compile_commands.json (AKA compilation database). 
> 2. cpp-linter works better with source paths and clang-tidy when the compilation database's path is explicitly defined via our [`database`](https://cpp-linter.github.io/cpp-linter-action/inputs-outputs/#database) option.

## Peculiar observations
It is odd that the `line-filter` uses a path different from the path to the analyzed source (`clang-tidy --line-filter='[{"name": "source-af-packet.c", ... src/source-af-packet.c`). If you're implicitly using a compilation data base (letting clang-tidy auto-detect one), then the `src/` part of the path might be getting excluded there which would explain why your customized command works.

It is also weird that `--extra-arg` is passed to clang-format without a value. I think this is a bug somehow.

**Comment by regit** [comment]
> Tip
> 
> 1. clang-tidy always works better when you give it a compile_commands.json (AKA compilation database).
> 2. cpp-linter works better with source paths and clang-tidy when the compilation database's path is explicitly defined via our [`database`](https://cpp-linter.github.io/cpp-linter-action/inputs-outputs/#database) option.
> 
> ## Peculiar observations
> It is odd that the `line-filter` uses a path different from the path to the analyzed source (`clang-tidy --line-filter='[{"name": "source-af-packet.c", ... src/source-af-packet.c`). If you're implicitly using a compilation data base (letting clang-tidy auto-detect one), then the `src/` part of the path might be getting excluded there which would explain why your customized command works.
> 
> It is also weird that `--extra-arg` is passed to clang-tidy without a value. I think this is a bug somehow.

Yes, I'm using a compilation database and the src directory is indeed not present in the file definition

```json
{ "directory": "/home/eric/git/suricata/src", "file": "source-af-packet.c", "output": "source-af-packet.o", "arguments": "lot of things"}
```

**Comment by 2bndy5** [comment]
> Is there an option to skip the source directory in the action ?

If everything needed (including compilation database) is located in src/ then you could tell cpp-linter to `cd src` with

```yml
- uses: cpp-linter/cpp-linter-action@v2
  with:
    repo-root: src
```
or using github actions syntax
```yml
- uses: cpp-linter/cpp-linter-action@v2
  working-directory: src
```
