### ISSUE TITLE
tidy-checks always applied nevetherless local .clang-tidy

### ISSUE THREAD

**Issue by ibis-hdl** [cpp-linter/cpp-linter-action#64]
Hi,

I'm starting with this action right now. Following the action log:
```
Run cpp-linter/cpp-linter-action@v1.4.2
  with:
    style: file
    version: 14
    database: build/ci-linux-clang
    thread-comments: false
    extensions: c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx
    tidy-checks: boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*
    repo-root: .
    verbosity: 10
    lines-changed-only: false
    files-changed-only: true
    ignore: .github
  env:
    CONAN_V2_MODE: 1
    GITHUB_TOKEN: ***
/usr/bin/docker run --name f1554982f9bdb02be47a699a3db07c25c8795_b963b1 --label 6f1554 --workdir /github/workspace --rm -e CONAN_V2_MODE -e GITHUB_TOKEN -e INPUT_STYLE -e INPUT_VERSION -e INPUT_DATABASE -e INPUT_THREAD-COMMENTS -e INPUT_EXTENSIONS -e INPUT_TIDY-CHECKS -e INPUT_REPO-ROOT -e INPUT_VERBOSITY -e INPUT_LINES-CHANGED-ONLY -e INPUT_FILES-CHANGED-ONLY -e INPUT_IGNORE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/gh-actions-test/gh-actions-test":"/github/workspace" 6f1554:982f9bdb02be47a699a3db07c25c8795  "--style=file" "--extensions=c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx" "--tidy-checks=boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*" "--repo-root=." "--version=14" "--verbosity=10" "--lines-changed-only=false" "--files-changed-only=true" "--thread-comments=false" "--ignore=.github" "--database=build/ci-linux-clang"
```
the CLI tidy checks are applied
```
"--tidy-checks=boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*"
```
which takes precedence over the ones in `.clang-tidy` follwing [Clang-Tidy](https://clang.llvm.org/extra/clang-tidy/):
```
Configuration files:
  clang-tidy attempts to read configuration for each source file from a
  .clang-tidy file located in the closest parent directory of the source
  file. If InheritParentConfig is true in a config file, the configuration file
  in the parent directory (if any exists) will be taken and current config file
  will be applied on top of the parent one. If any configuration options have
  a corresponding command-line option, command-line option takes precedence.
```

Is this correct? Following your action: "**tidy-checks** ... This option's value is appended to the value of the 'Checks' option in a .clang-tidy file (if any)." which is another interpretation (IMO they are simply overwritten).

Maybe the possibility to just dumping the configs makes it clear. 

Nevertheless, setting
```
      - uses: cpp-linter/cpp-linter-action@v1
        ...
        with:
          style: file
          tidy-checks: ''
```
would work for this?

**Comment by ibis-hdl** [comment]
ah, thanks for the answer. A quick google search found this URL for me; honestly - the concept of the llvm/clang page (I don't mean the style) doesn't make sense to me :(
Maybe you could introduce two config files options for each of clang-format and clang-tidy. This time I'll use `tidy-checks` option to a blank string. Further, you should add this to the README meanwhile (or definitely).

**Comment by 2bndy5** [comment]
> the concept of the llvm/clang page (I don't mean the style) doesn't make sense to me

Agreed. As an documentation advocate, the LLVM project's docs could use a face lift and possibly a re-organization. But this is the inherent nature of documenting a very complex and far reaching project under 1 domain.

> Maybe you could introduce two config files options for each of clang-format and clang-tidy

I can understand the need for explicit control, but clang-tidy and clang-format have different ways of handling the use of a config file.
- For clang-format, it was rather straight forward, thus the recommended `style: file` input option.
- But as you've pointed out, there is more intuition baked into clang-tidy (regarding config file) that makes it harder to explicitly control. Furthermore, adding a `tidy-config` input option (to allow adjusting the `--config=<string>` CLI option) to this action will mean having to deal with YAML/JSON syntax nested in a YAML configured workflow. Our input options cannot easily handle multi-lined values, and there's no value validation mechanism in place, So, it would be better to just use a well placed .clang-tidy file.

> Further, you should add this to the README meanwhile (or definitely).

Yes the blank string idea should definitely get added to the readme.

**Comment by ibis-hdl** [comment]
I see. Thanks for answer. Thanks for this action and your tiem to support!

Meanwhile, I run into another issue with regard to clang tidy's database (I'm not sure to open another issue - it's at yours). My action looks like

```
    - name: clang-format & clang-tidy
      uses: cpp-linter/cpp-linter-action@v1.4.2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: file
        version: 14
        # directory containing compilation database (compile_commands.json)
        database: build/ci-linux-clang
        # don't use action's default
        tidy-checks: ''
```
where `CMakePresets.json` contains
```
    ...
    "configurePresets": [
        {
            "name": "use-ninja",
            "generator": "Ninja",
            "cacheVariables": { "CMAKE_EXPORT_COMPILE_COMMANDS": "ON" }
        },
        {
            "name": "default-dirs",
            "binaryDir": "${sourceDir}/build/${presetName}",
            ...
        },
    ...
```
The action's log shows that it fails:
```
Run cpp-linter/cpp-linter-action@v1.4.2
/usr/bin/docker run --name f1554a9d49084b68a4119971e2b6f8bf850d2_02701c --label 6f1554 --workdir /github/workspace --rm -e CONAN_V2_MODE -e GITHUB_TOKEN -e INPUT_STYLE -e INPUT_VERSION -e INPUT_DATABASE -e INPUT_TIDY-CHECKS -e INPUT_THREAD-COMMENTS -e INPUT_EXTENSIONS -e INPUT_REPO-ROOT -e INPUT_VERBOSITY -e INPUT_LINES-CHANGED-ONLY -e INPUT_FILES-CHANGED-ONLY -e INPUT_IGNORE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/gh-actions-test/gh-actions-test":"/github/workspace" 6f1554:a9d49084b68a4119971e2b6f8bf850d2  "--style=file" "--extensions=c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx" "--tidy-checks=" "--repo-root=." "--version=14" "--verbosity=10" "--lines-changed-only=false" "--files-changed-only=true" "--thread-comments=false" "--ignore=.github" "--database=build/ci-linux-clang"
INFO:CPP Linter:Ignoring the following paths/files:
	./.github
INFO:CPP Linter:processing push event
Event json from the runner
Get list of specified source files
Performing checkup on source/main.cpp
  INFO:CPP Linter:Running "clang-tidy-14 --export-fixes=clang_tidy_output.yml -p /home/runner/work/gh-actions-test/build/ci-linux-clang source/main.cpp"
  DEBUG:CPP Linter:Output from clang-tidy:
  /github/workspace/source/main.cpp:4:10: error: 'fmt/format.h' file not found [clang-diagnostic-error]
```
Otherwise, running VS Code's devcontainer shows the same error with absolute paths (as action), while relative path seems to work:
```
vscode ➜ /workspaces/gh-actions-test (main ✗) $ clang-tidy-14 --export-fixes=clang_tidy_output.yml -p /home/runner/work/gh-actions-test/build/ci-linux-clang source/main.cpp
Error while trying to load a compilation database:
Could not auto-detect compilation database from directory "/home/runner/work/gh-actions-test/build/ci-linux-clang"
No compilation database found in /home/runner/work/gh-actions-test/build/ci-linux-clang or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
29893 warnings and 1 error generated.
Error while processing /workspaces/gh-actions-test/source/main.cpp.
...
vscode ➜ /workspaces/gh-actions-test (main ✗) $ clang-tidy-14 --export-fixes=clang_tidy_output.yml -p build/ci-linux-clang source/main.cpp
68700 warnings generated.
Suppressed 68700 warnings (68698 in non-user code, 2 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
```
I haven't the experience with clang-tidy using CLI args and python, so my guess is that's there is a wrong path (otherwise not very likely) :(

If relevant, the action is [here](https://github.com/ibis-hdl/gh-actions-test/blob/main/.github/workflows/cpp-linter.yml)
