### ISSUE TITLE
Propose: add probot-stale to move forward and cleanup issues

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#72]
We have several issues there are not been active for more than one month, some of them have been answered but the creator has not confirmed. [stale](https://github.com/probot/stale) can help us to automatically manage these issues. 

Here are the settings of `.github/stale.yml`

```yml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - bug
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

```
